/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vs.h"

bool_t
xdr_add_params (XDR *xdrs, add_params *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->p1))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->p2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_concat_params (XDR *xdrs, concat_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->str1, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->str2, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_split_return (XDR *xdrs, split_return *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->pre, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->post, ~0))
		 return FALSE;
	return TRUE;
}
