/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VS_H_RPCGEN
#define _VS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct return_twice {
	char *str1;
	char *str2;
};
typedef struct return_twice return_twice;

struct dir_node {
	char *desc;
	char *type;
	struct dir_node *next;
};
typedef struct dir_node dir_node;

struct quad_array {
	int size;
	struct {
		u_int elements_len;
		int *elements_val;
	} elements;
};
typedef struct quad_array quad_array;

#define VS11SERVER 0x20005123
#define VS11SERVERVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define vs_quad 1
extern  quad_array * vs_quad_1(int *, CLIENT *);
extern  quad_array * vs_quad_1_svc(int *, struct svc_req *);
#define vs_twice 2
extern  return_twice * vs_twice_1(char **, CLIENT *);
extern  return_twice * vs_twice_1_svc(char **, struct svc_req *);
#define vs_readdir 3
extern  dir_node * vs_readdir_1(char **, CLIENT *);
extern  dir_node * vs_readdir_1_svc(char **, struct svc_req *);
#define vs_shutdown 6
extern  void * vs_shutdown_1(void *, CLIENT *);
extern  void * vs_shutdown_1_svc(void *, struct svc_req *);
extern int vs11server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define vs_quad 1
extern  quad_array * vs_quad_1();
extern  quad_array * vs_quad_1_svc();
#define vs_twice 2
extern  return_twice * vs_twice_1();
extern  return_twice * vs_twice_1_svc();
#define vs_readdir 3
extern  dir_node * vs_readdir_1();
extern  dir_node * vs_readdir_1_svc();
#define vs_shutdown 6
extern  void * vs_shutdown_1();
extern  void * vs_shutdown_1_svc();
extern int vs11server_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_return_twice (XDR *, return_twice*);
extern  bool_t xdr_dir_node (XDR *, dir_node*);
extern  bool_t xdr_quad_array (XDR *, quad_array*);

#else /* K&R C */
extern bool_t xdr_return_twice ();
extern bool_t xdr_dir_node ();
extern bool_t xdr_quad_array ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VS_H_RPCGEN */
