/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vs.h"

quad_array *
vs_quad_1_svc(int *argp, struct svc_req *rqstp)
{
	static quad_array  result;

	/*
	 * insert server code here
	 */

	return &result;
}

return_twice *
vs_twice_1_svc(char **argp, struct svc_req *rqstp)
{
	static return_twice  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
vs_readdir_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

void *
vs_shutdown_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}
